import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

@Entity({ name: 'class_session' })
export class ClassSessionEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'tenant_id', type: 'uuid' })
  tenantId: string;

  @Column({ name: 'class_group_id', type: 'uuid' })
  classGroupId: string;

  // RULE-INST-07: NULL means "inherit class_group.roomId" (the common case
  // now that room is assigned once at the turma level); a non-null value is
  // a pontual (one-off) override for this specific session only
  // (RULE-INST-04's per-session edit of horário/sala/data).
  @Column({ name: 'room_id', type: 'uuid', nullable: true })
  roomId: string | null;

  @Column({ name: 'scheduled_start', type: 'timestamptz' })
  scheduledStart: Date;

  @Column({ name: 'scheduled_end', type: 'timestamptz' })
  scheduledEnd: Date;

  // RULE-INST-04: 'scheduled' = untouched, auto-generated by the recurring
  // grade, the only status ScheduleRegenerationService may overwrite;
  // 'edited' = a pontual edit was applied to this session (time/room/date),
  // preserved and excluded from regeneration; 'cancelled' = cancelled
  // (manually, or automatically by a same-day Holiday), preserved (never
  // deleted) along with any check-in/pending-review history already
  // attached to it.
  @Column({ type: 'varchar', length: 20, default: 'scheduled' })
  status: string;

  // Snapshot of attendance_config at the time of the session (RULE-ATT-04/05/14) —
  // later config changes must not retroactively recalculate past sessions.
  @Column({ name: 'min_attendance_percentage_snapshot', type: 'numeric', precision: 5, scale: 2 })
  minAttendancePercentageSnapshot: number;

  @Column({ name: 'tolerance_minutes_snapshot', type: 'int' })
  toleranceMinutesSnapshot: number;

  @Column({ name: 'post_tolerance_behavior_snapshot', type: 'varchar', length: 20 })
  postToleranceBehaviorSnapshot: string;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}
