import { MigrationInterface, QueryRunner } from 'typeorm';

// RULE-INST-07: room_id becomes nullable on class_session — NULL now means
// "inherit class_group.room_id" (the common case, since RULE-INST-07 moves
// the single point of room assignment to the turma); a non-null value means
// a one-off override for that specific session only (RULE-INST-04's
// pontual-edit item #3: horário/sala/data are each editable per-session
// without touching the rest of the turma's schedule). Existing rows all
// keep their current explicit room_id (still a valid override-shaped value
// even though it predates the inheritance model) — additive/backward
// compatible, same DROP NOT NULL pattern already used by
// AllowNullDeviceIdForAppCheckin.
//
// RULE-INST-04 (third-round update, item #1): cancelling a session must
// preserve it (and any check-in/pending-review history already attached to
// it), not delete it. `status` models this: 'scheduled' = untouched,
// auto-generated by the recurring grade, and the only value
// ScheduleRegenerationService is allowed to overwrite/replace when the
// grade changes; 'edited' = a pontual edit (time/room/date) was applied to
// this specific session — preserved, excluded from regeneration per the
// rule's item #5; 'cancelled' = cancelled (manually, or automatically by a
// same-day Holiday per the rule's item #4) — preserved, also excluded from
// regeneration. One column carries both the business-facing status (what
// RULE-INST-06's operational screens and the App Mobile's "aula cancelada"
// marker display) and the technical regeneration-eligibility signal,
// instead of splitting them into two columns with no independent meaning of
// their own.
export class AddClassSessionScheduleFields1755857000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE class_session ALTER COLUMN room_id DROP NOT NULL');

    await queryRunner.query("ALTER TABLE class_session ADD COLUMN status varchar(20) NOT NULL DEFAULT 'scheduled'");
    await queryRunner.query(`
      ALTER TABLE class_session
      ADD CONSTRAINT class_session_status_check CHECK (status IN ('scheduled', 'edited', 'cancelled'))
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE class_session DROP CONSTRAINT IF EXISTS class_session_status_check');
    await queryRunner.query('ALTER TABLE class_session DROP COLUMN IF EXISTS status');

    // Only safe to revert cleanly if no row was left with a NULL room_id in
    // the meantime (the whole point of this migration) — same documented
    // limitation as AllowNullDeviceIdForAppCheckin's down(): this
    // intentionally does not delete/backfill data to force the column back
    // to NOT NULL.
    await queryRunner.query('ALTER TABLE class_session ALTER COLUMN room_id SET NOT NULL');
  }
}
