import { api, buildQuery } from '../../lib/api-client';

// RULE-INST-04/07/10: the recurring weekly grade a turma's concrete
// class_session rows are generated/regenerated from. dayOfWeek follows JS
// Date.getDay() (0 = domingo .. 6 = sábado), matching the backend entity.
export interface ScheduleSlot {
  id: string;
  classGroupId: string;
  // RULE-INST-14: which of the turma's matérias this weekly slot teaches —
  // a Mon/Wed turma can hold Matemática na segunda e Física na quarta.
  subjectId: string;
  dayOfWeek: number;
  startTime: string; // "HH:mm:ss"
  endTime: string; // "HH:mm:ss"
  createdAt: string;
  updatedAt: string;
}

export interface CreateScheduleSlotInput {
  subjectId: string;
  dayOfWeek: number;
  startTime: string; // "HH:mm"
  endTime: string; // "HH:mm"
}

export interface GenerateSessionsResult {
  created: number;
  skipped: number;
}

export async function listScheduleSlots(classGroupId: string): Promise<ScheduleSlot[]> {
  return api.get(`/v1/class-groups/${classGroupId}/schedule-slots`);
}

export async function createScheduleSlot(classGroupId: string, input: CreateScheduleSlotInput): Promise<ScheduleSlot> {
  return api.post(`/v1/class-groups/${classGroupId}/schedule-slots`, input);
}

export async function deleteScheduleSlot(classGroupId: string, slotId: string): Promise<void> {
  await api.delete(`/v1/class-groups/${classGroupId}/schedule-slots/${slotId}`);
}

// RULE-INST-04: bulk-generates class_session rows for the whole turma term
// period from its recurring grade, skipping holidays. The backend responds
// 400 if the turma has no roomId/termStartDate/termEndDate yet, or 409 on a
// room/teacher schedule conflict (RULE-INST-10) — both surface through
// errorMessage()/ErrorBanner like any other mutation error, no special
// handling needed here.
export async function generateSessions(classGroupId: string): Promise<GenerateSessionsResult> {
  return api.post(`/v1/class-groups/${classGroupId}/schedule-slots/generate-sessions`);
}

// 'scheduled' = untouched, auto-generated by the recurring grade; 'edited' =
// a pontual edit was applied (time/room/date); 'cancelled' = cancelled
// (manually, or automatically by a same-day Holiday) — never deleted, so
// history stays attached (RULE-INST-04, third-round update, item #1).
export type ClassSessionStatus = 'scheduled' | 'edited' | 'cancelled';

export interface ClassSession {
  id: string;
  classGroupId: string;
  // RULE-INST-14: the matéria THIS occurrence is about — propagated from the
  // slot that generated it, or chosen when the aula is created avulsa.
  subjectId: string;
  // RULE-INST-07: null means "inherit the room assigned on the turma
  // itself" — only a pontual edit overrides this per-session.
  roomId: string | null;
  scheduledStart: string;
  scheduledEnd: string;
  status: ClassSessionStatus;
  minAttendancePercentageSnapshot: number;
  toleranceMinutesSnapshot: number;
  postToleranceBehaviorSnapshot: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateClassSessionInput {
  classGroupId: string;
  subjectId: string;
  roomId?: string;
  scheduledStart: string;
  scheduledEnd: string;
}

// RULE-INST-04 (third-round update, item #3): horário, sala e data são os
// três campos editáveis pontualmente. roomId omitido mantém a sala atual da
// sessão (que pode já ser uma sobreposição anterior, ou null = herdada).
export interface EditClassSessionInput {
  scheduledStart: string;
  scheduledEnd: string;
  roomId?: string;
}

export interface EditClassSessionResult {
  classSessionId: string;
  status: ClassSessionStatus;
  scheduledStart: string;
  scheduledEnd: string;
  roomId: string | null;
}

export interface CancelClassSessionResult {
  classSessionId: string;
  status: ClassSessionStatus;
}

export async function listClassSessions(classGroupId?: string, subjectId?: string): Promise<ClassSession[]> {
  return api.get(`/v1/class-sessions${buildQuery({ classGroupId, subjectId })}`);
}

// Ad-hoc single-session creation — kept alongside the recurring-grade
// generation above. The backend intentionally still supports this as a
// separate, always-available path (see class-session.service.ts's own
// comment: "the third place class_session rows get written"), running the
// same RULE-INST-10 conflict check as the bulk generator.
export async function createClassSession(input: CreateClassSessionInput): Promise<{ classSessionId: string }> {
  return api.post('/v1/class-sessions', input);
}

export async function editClassSession(
  classSessionId: string,
  input: EditClassSessionInput,
): Promise<EditClassSessionResult> {
  return api.patch(`/v1/class-sessions/${classSessionId}`, input);
}

export async function cancelClassSession(classSessionId: string): Promise<CancelClassSessionResult> {
  return api.patch(`/v1/class-sessions/${classSessionId}/cancel`);
}
