export enum IngestionEventType {
  TAG_CHECKIN = 'TAG_CHECKIN',
  FACIAL_CHECKIN = 'FACIAL_CHECKIN',
  ROOM_ENTRY = 'ROOM_ENTRY',
  ROOM_EXIT = 'ROOM_EXIT',
  CAMERA_COUNT = 'CAMERA_COUNT',
  CUSTOM = 'CUSTOM',
}
